import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "./globals.css";
import Link from "next/link";
import { getSession } from "@auth0/nextjs-auth0";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getSession();

  return (
    <html lang="en">
      <UserProvider>
        <body>
          <header className="flex items-center justify-end px-12">
            <nav className="flex items-center gap-10 py-4">
              {session && (
                <>
                  <Link href="/me">My Inspirations</Link>
                  <Link href="/marketplace">Marketplace</Link>
                  <a href="/api/auth/logout" className="bg-rose-500 px-4 py-2">
                    Log out
                  </a>
                </>
              )}
            </nav>
          </header>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
