import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <header>
            <nav>
              <a href="/api/auth/logout" className="bg-rose-500 px-4 py-2">
                Log out
              </a>
            </nav>
          </header>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
